config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, expect: [:update]
  resources :foods, only: [:index, :show, :destroy, :new, :create]

  resources :recipe_foods, only: [:edit, :create, :update, :destroy, :new]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :toggle_public
    end
  end
  get '/public_recipes', to: 'recipes#public_recipes'
  get '/shopping_list', to: 'shopping_list#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :user_id, presence: true
  validates :cooking_time, numericality: { greater_than: 0 }
  validates :prep_time, numericality: { greater_than: 0 }

  def toggle_public
    update(public: !public)
  end

  def add_to_shopping_list
    update(add_to_shopping_list: !add_to_shopping_list)
  end
end

app/controllers/recipes_controller.rb
# app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @recipes = Recipe.includes([:user]).where(user: current_user)
  end

  def show
    # @recipe = Recipe.find(params[:id])
    # @foods = Food.joins(:recipe_foods).where(recipe_foods: { recipe_id: @recipe.id })
    @recipe = Recipe.includes(:user, :recipe_foods).find(params[:id])
    @recipe_food = RecipeFood.new

    if @recipe.public? || current_user == @recipe.user
      # Display the recipe details as in the wireframe
    else
      redirect_to recipes_path, alert: 'You are not authorized to view this private recipe.'
    end
    @foods = Food.joins(:recipe_foods).where(recipe_foods: { recipe_id: @recipe.id })

    # Calculate total food items
    @total_food_items = @foods.length

    # Calculate total price
    @total_price = @foods.sum(&:price)
    # fetch list of recipes foods
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.update(public: !@recipe.public)
    redirect_to @recipe, notice: 'Public status successfully updated.'
  end

  # def edit
  #   @recipe = Recipe.find(params[:id])
  #   if current_user != @recipe.user
  #     redirect_to recipes_path, alert: "You are not authorized to edit this recipe."
  #   end
  # end

  # def update
  #   @recipe = Recipe.find(params[:id])
  #   if current_user == @recipe.user
  #     if @recipe.update(recipe_params)
  #       redirect_to @recipe, notice: "Recipe was successfully updated."
  #     else
  #       render :edit
  #     end
  #   else
  #     redirect_to recipes_path, alert: "You are not authorized to edit this recipe."
  #   end
  # end
  def public_recipes
    @public = Recipe.includes(:user, :recipe_foods).where(public: true).order('created_at DESC')
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
    else
      redirect_to recipes_path, alert: 'You are not authorized to delete this recipe.'
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :prep_time, :cooking_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, url: recipes_path, local: true, class: "recipe-form") do |form| %>
  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-row">
    <div class="form-field">
      <%= form.label :cooking_time %>
      <%= form.number_field :cooking_time, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :prep_time %>
      <%= form.number_field :prep_time, class: "form-control" %>
    </div>
  </div>

  <div class="form-check">
    <%= form.label :public, class: "form-check-label" %>
    <%= form.check_box :public, class: "form-check-input" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit "Save Recipe", class: "submit-btn" %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<h2>Recipes list</h2>

<%= link_to "New Recipe", new_recipe_path, class: "new-recipe-btn" %>

<ul>
  <% @recipes.each do |recipe| %>
    <li class="recipe-element">
    <div class="title-del">
    <%= link_to recipe.name, recipe_path(recipe), class: "recipe.name" %>
     <%= button_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "del-btn", remote: true %>
    </div>
      <p class="description"><%=recipe.description%></p>
    </li>
  <% end %>
</ul>

app/views/recipes/new.html.erb
<h2 class="form-title">New Recipe</h2>

<%= render 'form' %>

<%= link_to "Back to Recipes", recipes_path, class: "back-link" %>

app/views/recipes/public_recipes.html.erb
<%= stylesheet_link_tag 'Food_List', media: 'all' %>

<h1 class="professional-h1">Public Recipes</h1>

<% if @public.length > 0 %>
  <table class="recipe-items">
    <tr>
      <th>Recipe Name</th>
      <th>By</th>
      <th>Total Food Items</th>
      <th>Total Price</th>
    </tr>
    <% @public.each do |recipe| %>
      <tr>
        <td class="recipe_name"><%= link_to recipe.name, recipe_path(recipe), class: "recipe.name" %></td>
        <td class="recipe_details">by: <%= recipe.user.name %></td>
        <td class="recipe_details"><%= recipe.recipe_foods.length %></td>
        <% total_price = recipe.recipe_foods.sum { |food| food.food.price } %>
        <td class="recipe_price">$<%= total_price %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h2 class="no-recipes">No Public Recipies Found</h2>
<% end %>

app/views/recipes/public_recipies.html.erb
<%= stylesheet_link_tag 'Food_List', media: 'all' %>

<h1 class="professional-h1">Public Recipies</h1>

<% if @public.length > 0 %>
  <table class="recipe-items">
    <tr>
      <th>Recipe Name</th>
      <th>By</th>
      <th>Total Food Items</th>
      <th>Total Price</th>
    </tr>
    <% @public.each do |recipe| %>
      <tr>
        <td class="recipe_name"><%= recipe.name %></td>
        <td class="recipe_details">by: <%= recipe.user.name %></td>
        <td class="recipe_details"><%= recipe.recipe_foods.length %></td>

        <% total_price = recipe.recipe_foods.sum { |food| food.food.price } %>
        <td class="recipe_price">$<%= total_price %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <h2 class="no-recipes">No Public Recipies Found</h2>
<% end %>

app/views/recipes/show.html.erb
<div class="center-content">
  <div class="recipe-details">
    <h2 class="recipe-name"><%= @recipe.name %></h2>
<%= button_to toggle_public_recipe_path(@recipe), method: :patch, class: "toggle-public-btn" do %>
  <%= @recipe.public? ? "Make Private" : "Make Public" %>
<% end %>
<p class="recipe-description"><strong>Description:</strong> <%= @recipe.description %></p>
<p><strong>Prep Time:</strong> <%= @recipe.prep_time %> minutes</p>
<p><strong>Cooking Time:</strong> <%= @recipe.cooking_time %> minutes</p>
<p><strong>Public:</strong> <%= @recipe.public ? "Yes" : "No" %></p>

<div class="action-btns">
<%= link_to "Back to Recipes", recipes_path, class: "back-btn" %>
<%= link_to "Shopping List", shopping_list_path, class: "back-btn" %>

<% if current_user == @recipe.user %>
  <%= link_to "Add Ingredient", new_recipe_food_path(recipe_id: @recipe.id), class: "add-food-item-btn" %>
<% end %>
</div>
<hr>


<!-- Display existing recipe foods (ingredients) here -->
<h3 class="food-items-heading">Food Items</h3>
<table class="food-items-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_foods.each do |recipe_food| %>
      <tr>
        <td><%= recipe_food.food.name %></td>
        <td><%= recipe_food.food.measurement_unit %></td>
        <td><%= recipe_food.quantity %></td>
        <td>$<%= recipe_food.food.price * recipe_food.quantity %></td>
        <td>
          <%= link_to "Edit", edit_recipe_food_path(recipe_food), class: "edit-food-btn" %>
          <%= link_to "Remove", recipe_food_path(recipe_food), method: :delete, data: { confirm: "Are you sure you want to remove this food item from the recipe?" }, class: "remove-food-btn" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>