config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, expect: [:update]
  resources :foods, only: [:index, :show, :destroy, :new, :create]

  resources :recipe_foods, only: [:edit, :create, :update, :destroy, :new]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :toggle_public
    end
  end
  get '/public_recipes', to: 'recipes#public_recipes'
  get '/shopping_list', to: 'shopping_list#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
  validates :quantity, presence: true
  validates :price, presence: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  def index
    @foods = if user_signed_in?
               Food.where(user: current_user)
             else
               []
             end
  end

  def new
    @food = Food.new
  end

  def show
    @food = Food.find_by_id(params[:id])
  end

  def create
    @food = Food.new(foods_data)
    @food.user_id = current_user.id

    if @food.save
      redirect_to foods_path
    else
      render :new, status: 422
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      redirect_to foods_path, notice: 'Food has been deleted successfully'
    else
      redirect_to foods_path, alert: 'An error occured while deleting the food'
    end
  end

  private

  def foods_data
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'Food_List', media: 'all' %>

<div class="main-cont">
  <h1>Food List</h1>
  <div class="btn-cont"><%= link_to 'Add Food', '/foods/new', class: 'add-food-button' %></div>

  <% if @foods.any? %>
    <table class="list-items">
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= link_to "#{food.name}", food_path(food.id), class: 'food-link' %></td>
            <td><%= food.measurement_unit %></td>
            <td>$<%= food.price %></td>
            <td><%= button_to "Delete", food_path(food.id), method: :delete, data: { confirm: "Are you certain you wish to delete this food item?" }, class: 'delete-button' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No foods found.</p>
  <% end %>
</div>

app/views/foods/new.html.erb
<%= stylesheet_link_tag 'Food_List', media: 'all' %>

<div class="form-cont">
<h1>Add new food here</h1>

<% if @food.errors.any? %>
  <div class="error-alerts">
    <p>
      <%= pluralize(@food.errors.count, "error") %>
      Found:
    </p>
    <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <%= form_with model: @food, url: foods_path, method: :post do |form| %>
    <div class="form-title">Name:</div>
    <%= form.text_field :name, class: "form-text" %>

    <div class="form-title">Measurement Unit:</div>
    <%= form.text_field :measurement_unit, class: "form-text" %>

    <div class="form-title">Price:</div>
    <%= form.text_field :price, class: "form-text" %>

    <div class="form-title">Quantity:</div>
    <%= form.number_field :quantity, class: "form-text" %>
    <%= form.submit "Add Food", class: "form-btn" %>
  <% end %>
</div>

app/views/foods/show.html.erb
<%= stylesheet_link_tag 'Food_List', media: 'all' %>

<div class = "food-display">
<h1><%= @food.name %></h1>
<h2>Measurement: <%= @food.measurement_unit %></h2>
<h2>Price in $: <%= @food.price %></h2>
<h2>Quantity: <%= @food.quantity %></h2>
</div>