config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, expect: [:update]
  resources :foods, only: [:index, :show, :destroy, :new, :create]

  resources :recipe_foods, only: [:edit, :create, :update, :destroy, :new]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :toggle_public
    end
  end
  get '/public_recipes', to: 'recipes#public_recipes'
  get '/shopping_list', to: 'shopping_list#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_recipe, only: %i[show toggle_public]

  def show
    @recipe_food = RecipeFood.new # Initialize a new RecipeFood instance for the form
    # Rest of the code
  end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_id: params[:recipe_id])
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)

    # Set the recipe ID to associate the food item with the current recipe
    @recipe_food.recipe = Recipe.find(params[:recipe_id])

    if @recipe_food.save
      redirect_to @recipe_food.recipe, notice: 'Food item was successfully added to the recipe.'
    else
      # Handle validation errors if any
      @recipe = @recipe_food.recipe
      render 'recipes/show'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/new.html.erb
<h3>Add New Food Item</h3>
  <%= form_with(model: @recipe_food, url: recipe_foods_path(recipe_id: @recipe.id), local: true) do |form| %>
    <div class="field">
      <%= form.label :food_id, "Food Item" %>
      <%= form.collection_select(:food_id, Food.where(user_id: current_user), :id, :name) %>
    </div>

    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity %>
    </div>

    <div class="actions">
      <%= form.submit "Add Food Item" %>
    </div>
  <% end %>