config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :recipes, expect: [:update]
  resources :foods, only: [:index, :show, :destroy, :new, :create]

  resources :recipe_foods, only: [:edit, :create, :update, :destroy, :new]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :toggle_public
    end
  end
  get '/public_recipes', to: 'recipes#public_recipes'
  get '/shopping_list', to: 'shopping_list#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "recipes", media: "all" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Recipes", recipes_path %></li>
        <li><%= link_to "New Recipe", new_recipe_path %></li>
        <li><%= link_to "Foods", foods_path %></li>
        <li><%= link_to "New Food", new_food_path %></li>
        <li><%= link_to "Public Recipes", public_recipes_path %></li>
        <li><%= link_to "Shopping List", shopping_list_path %></li>
      </ul>
      <div> <% if user_signed_in? %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "signout-btn" %>
        <% else %>
          <%= button_to "Login", new_user_session_path %>
        <% end %>
        </div>
    </nav>
    <%= yield %>
  </body>
</html>